version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgrescontainer24
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - springangularproject

networks:
  springangularproject:
    driver: bridge

volumes:
  postgres:
    driver: local
