version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgrescontainer24
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - springangularproject

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025


networks:
  springangularproject:
    driver: bridge

volumes:
  postgres:
    driver: local